interface ImportMetaEnv {
  VITE_EVENTS_QUEUE_REGION: string,
  VITE_EVENTS_QUEUE_ENDPOINT: string,
  VITE_EVENTS_QUEUE_PATH: string,
  VITE_EVENTS_QUEUE_CREDENTIALS_KEY_ID: string,
  VITE_EVENTS_QUEUE_CREDENTIALS_ACCESS_KEY: string,
  VITE_ACK_EVENTS_QUEUE_REGION: string,
  VITE_ACK_EVENTS_QUEUE_ENDPOINT: string,
  VITE_ACK_EVENTS_QUEUE_PATH: string,
  VITE_ACK_EVENTS_QUEUE_CREDENTIALS_KEY_ID: string,
  VITE_ACK_EVENTS_QUEUE_CREDENTIALS_ACCESS_KEY: string,
  VITE_BACKEND_API_BASE: string,
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
